name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Deps
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload Arifacts
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build-files